[package]
name    = "ail-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
otel = ["dep:tracing"]

[dependencies]
ail-core           = { workspace = true }
ail-verify         = { workspace = true }
blake3             = { workspace = true }
ciborium           = { workspace = true }
serde              = { workspace = true }
wasm-encoder       = { workspace = true }
cranelift-codegen  = { workspace = true }
cranelift-frontend = { workspace = true }
cranelift-module   = { workspace = true }
cranelift-native   = { workspace = true }
cranelift-object   = { workspace = true }
tracing            = { workspace = true, optional = true }

[dev-dependencies]
ail-testkit  = { workspace = true }
wasmparser   = { workspace = true }
criterion    = { version = "0.5", features = ["html_reports"] }
tracing      = { workspace = true }

[[bench]]
name    = "large_graph"
harness = false

[lints]
workspace = true
