[package]
name    = "ail-runtime"
version.workspace = true
edition.workspace = true

[features]
otel = ["dep:tracing"]

[dependencies]
ail-package = { workspace = true }
blake3      = { workspace = true }
ciborium    = { workspace = true }
serde       = { workspace = true }
wasmtime    = { workspace = true }
tracing     = { workspace = true, optional = true }

[dev-dependencies]
ail-compiler  = { workspace = true }
ail-core      = { workspace = true }
ail-verify    = { workspace = true }
wasm-encoder  = { workspace = true }

[lints]
workspace = true
