use super::AclSymbol;

pub(super) const AIL_SOURCE_BUILTIN_SYMBOLS: &[AclSymbol] = &[
    AclSymbol {
        label: "add",
        detail: "AIL source Int builtin",
        documentation: "Adds two Int values and returns an Int.",
        insert_text: "add(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "sub",
        detail: "AIL source Int builtin",
        documentation: "Subtracts the second Int from the first and returns an Int.",
        insert_text: "sub(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "mul",
        detail: "AIL source Int builtin",
        documentation: "Multiplies two Int values and returns an Int.",
        insert_text: "mul(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "div",
        detail: "AIL source Int builtin",
        documentation: "Divides the first Int by the second and returns an Int.",
        insert_text: "div(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "eq",
        detail: "AIL source comparison builtin",
        documentation: "Compares two values of the same inferred type and returns Bool.",
        insert_text: "eq(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "gt",
        detail: "AIL source Int comparison builtin",
        documentation: "Returns Bool after checking whether the first Int is greater than the second.",
        insert_text: "gt(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_min",
        detail: "AIL source Int bounds helper",
        documentation: "Returns the smaller of two Int values.",
        insert_text: "int_min(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_max",
        detail: "AIL source Int bounds helper",
        documentation: "Returns the larger of two Int values.",
        insert_text: "int_max(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_clamp",
        detail: "AIL source Int bounds helper",
        documentation: "Constrains an Int value to an inclusive low/high range.",
        insert_text: "int_clamp(${1:value}, ${2:low}, ${3:high})",
    },
    AclSymbol {
        label: "int_abs_or",
        detail: "AIL source Int safety helper",
        documentation: "Returns the absolute value of an Int, or fallback for the minimum Int overflow case.",
        insert_text: "int_abs_or(${1:value}, ${2:fallback})",
    },
    AclSymbol {
        label: "int_neg_or",
        detail: "AIL source Int safety helper",
        documentation: "Negates an Int value, or returns fallback for the minimum Int overflow case.",
        insert_text: "int_neg_or(${1:value}, ${2:fallback})",
    },
    AclSymbol {
        label: "int_add_or",
        detail: "AIL source Int safety helper",
        documentation: "Adds two Int values, or returns fallback on signed overflow.",
        insert_text: "int_add_or(${1:left}, ${2:right}, ${3:fallback})",
    },
    AclSymbol {
        label: "int_sub_or",
        detail: "AIL source Int safety helper",
        documentation: "Subtracts two Int values, or returns fallback on signed overflow.",
        insert_text: "int_sub_or(${1:left}, ${2:right}, ${3:fallback})",
    },
    AclSymbol {
        label: "int_mul_or",
        detail: "AIL source Int safety helper",
        documentation: "Multiplies two Int values, or returns fallback on signed overflow.",
        insert_text: "int_mul_or(${1:left}, ${2:right}, ${3:fallback})",
    },
    AclSymbol {
        label: "int_saturating_add",
        detail: "AIL source Int safety helper",
        documentation: "Adds two Int values, clamping to Int bounds on signed overflow.",
        insert_text: "int_saturating_add(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_saturating_sub",
        detail: "AIL source Int safety helper",
        documentation: "Subtracts two Int values, clamping to Int bounds on signed overflow.",
        insert_text: "int_saturating_sub(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_saturating_mul",
        detail: "AIL source Int safety helper",
        documentation: "Multiplies two Int values, clamping to Int bounds on signed overflow.",
        insert_text: "int_saturating_mul(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_saturating_neg",
        detail: "AIL source Int safety helper",
        documentation: "Negates an Int value, clamping the minimum Int overflow case to Int max.",
        insert_text: "int_saturating_neg(${1:value})",
    },
    AclSymbol {
        label: "int_wrapping_add",
        detail: "AIL source Int explicit wrapping helper",
        documentation: "Adds two Int values with explicit two's-complement wrapping semantics.",
        insert_text: "int_wrapping_add(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_wrapping_sub",
        detail: "AIL source Int explicit wrapping helper",
        documentation: "Subtracts two Int values with explicit two's-complement wrapping semantics.",
        insert_text: "int_wrapping_sub(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_wrapping_mul",
        detail: "AIL source Int explicit wrapping helper",
        documentation: "Multiplies two Int values with explicit two's-complement wrapping semantics.",
        insert_text: "int_wrapping_mul(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_wrapping_neg",
        detail: "AIL source Int explicit wrapping helper",
        documentation: "Negates an Int value with explicit two's-complement wrapping semantics.",
        insert_text: "int_wrapping_neg(${1:value})",
    },
    AclSymbol {
        label: "int_bit_and",
        detail: "AIL source Int bitwise helper",
        documentation: "Computes the bitwise AND of two Int values.",
        insert_text: "int_bit_and(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_bit_or",
        detail: "AIL source Int bitwise helper",
        documentation: "Computes the bitwise OR of two Int values.",
        insert_text: "int_bit_or(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_bit_xor",
        detail: "AIL source Int bitwise helper",
        documentation: "Computes the bitwise XOR of two Int values.",
        insert_text: "int_bit_xor(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_bit_not",
        detail: "AIL source Int bitwise helper",
        documentation: "Computes the bitwise NOT of an Int value.",
        insert_text: "int_bit_not(${1:value})",
    },
    AclSymbol {
        label: "int_shift_left",
        detail: "AIL source Int bit shift helper",
        documentation: "Shifts an Int value left by the given Int amount using wrapping shift-count semantics.",
        insert_text: "int_shift_left(${1:value}, ${2:amount})",
    },
    AclSymbol {
        label: "int_shift_right",
        detail: "AIL source Int bit shift helper",
        documentation: "Shifts an Int value right by the given Int amount using arithmetic signed semantics and wrapping shift-count semantics.",
        insert_text: "int_shift_right(${1:value}, ${2:amount})",
    },
    AclSymbol {
        label: "int_shift_right_unsigned",
        detail: "AIL source Int bit shift helper",
        documentation: "Shifts an Int value right by the given Int amount using logical unsigned semantics and wrapping shift-count semantics.",
        insert_text: "int_shift_right_unsigned(${1:value}, ${2:amount})",
    },
    AclSymbol {
        label: "int_div_or",
        detail: "AIL source Int safety helper",
        documentation: "Divides two Int values, or returns fallback on divide-by-zero or signed overflow.",
        insert_text: "int_div_or(${1:value}, ${2:divisor}, ${3:fallback})",
    },
    AclSymbol {
        label: "int_rem_or",
        detail: "AIL source Int safety helper",
        documentation: "Computes Int remainder, or returns fallback on divide-by-zero or signed overflow.",
        insert_text: "int_rem_or(${1:value}, ${2:divisor}, ${3:fallback})",
    },
    AclSymbol {
        label: "concat",
        detail: "AIL source Text builtin",
        documentation: "Concatenates two Text values and returns Text.",
        insert_text: "concat(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "len",
        detail: "AIL source sized builtin",
        documentation: "Returns the Int length of a Text or List value.",
        insert_text: "len(${1:value})",
    },
    AclSymbol {
        label: "text_length",
        detail: "AIL source Text helper",
        documentation: "Returns the byte length of a Text value.",
        insert_text: "text_length(${1:value})",
    },
    AclSymbol {
        label: "list_length",
        detail: "AIL source List helper",
        documentation: "Returns the length of a List value.",
        insert_text: "list_length(${1:list})",
    },
    AclSymbol {
        label: "list.length",
        detail: "AIL source List helper",
        documentation: "Dotted alias that returns the length of a List value.",
        insert_text: "list.length(${1:list})",
    },
    AclSymbol {
        label: "is_empty",
        detail: "AIL source sized predicate",
        documentation: "Returns true when a Text or List value has length 0.",
        insert_text: "is_empty(${1:value})",
    },
    AclSymbol {
        label: "text_is_empty",
        detail: "AIL source Text predicate",
        documentation: "Returns true when a Text value has length 0.",
        insert_text: "text_is_empty(${1:value})",
    },
    AclSymbol {
        label: "list_is_empty",
        detail: "AIL source List predicate",
        documentation: "Returns true when a List value has length 0.",
        insert_text: "list_is_empty(${1:list})",
    },
    AclSymbol {
        label: "list.is_empty",
        detail: "AIL source List predicate",
        documentation: "Dotted alias that returns true when a List value has length 0.",
        insert_text: "list.is_empty(${1:list})",
    },
    AclSymbol {
        label: "text_eq",
        detail: "AIL source Text predicate",
        documentation: "Compares two Text values by content.",
        insert_text: "text_eq(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "text_trim",
        detail: "AIL source Text helper",
        documentation: "Returns Text with leading and trailing ASCII whitespace removed.",
        insert_text: "text_trim(${1:value})",
    },
    AclSymbol {
        label: "text_contains",
        detail: "AIL source Text predicate",
        documentation: "Returns true when the first Text contains the second Text.",
        insert_text: "text_contains(${1:haystack}, ${2:needle})",
    },
    AclSymbol {
        label: "text_index_of",
        detail: "AIL source Text search",
        documentation: "Returns the zero-based byte index of needle inside Text, or -1 when absent.",
        insert_text: "text_index_of(${1:haystack}, ${2:needle})",
    },
    AclSymbol {
        label: "text_parse_int_or",
        detail: "AIL source Text parser",
        documentation: "Parses an ASCII decimal Int from Text, or returns fallback when invalid.",
        insert_text: "text_parse_int_or(${1:value}, ${2:fallback})",
    },
    AclSymbol {
        label: "text_byte_at_or",
        detail: "AIL source Text helper",
        documentation: "Returns the byte value at index, or fallback when the index is out of bounds.",
        insert_text: "text_byte_at_or(${1:value}, ${2:index}, ${3:fallback})",
    },
    AclSymbol {
        label: "text_slice",
        detail: "AIL source Text helper",
        documentation: "Returns a safe byte slice of Text from start for length bytes.",
        insert_text: "text_slice(${1:value}, ${2:start}, ${3:length})",
    },
    AclSymbol {
        label: "text_replace_first",
        detail: "AIL source Text helper",
        documentation: "Replaces the first occurrence of needle in Text, or returns the original Text when absent.",
        insert_text: "text_replace_first(${1:value}, ${2:needle}, ${3:replacement})",
    },
    AclSymbol {
        label: "text_starts_with",
        detail: "AIL source Text predicate",
        documentation: "Returns true when Text starts with the given prefix.",
        insert_text: "text_starts_with(${1:haystack}, ${2:prefix})",
    },
    AclSymbol {
        label: "text_ends_with",
        detail: "AIL source Text predicate",
        documentation: "Returns true when Text ends with the given suffix.",
        insert_text: "text_ends_with(${1:haystack}, ${2:suffix})",
    },
    AclSymbol {
        label: "Some",
        detail: "AIL source Option constructor",
        documentation: "Builds Option<T> with a present value.",
        insert_text: "Some(${1:value})",
    },
    AclSymbol {
        label: "None",
        detail: "AIL source Option constructor",
        documentation: "Builds an empty Option<T> value.",
        insert_text: "None",
    },
    AclSymbol {
        label: "Ok",
        detail: "AIL source Result constructor",
        documentation: "Builds a Result<T,E> success value.",
        insert_text: "Ok(${1:value})",
    },
    AclSymbol {
        label: "Err",
        detail: "AIL source Result constructor",
        documentation: "Builds a Result<T,E> error value.",
        insert_text: "Err(${1:error})",
    },
    AclSymbol {
        label: "unwrap_or",
        detail: "AIL source Option helper",
        documentation: "Returns the value inside Option<T>, or a fallback when it is None.",
        insert_text: "unwrap_or(${1:option}, ${2:fallback})",
    },
    AclSymbol {
        label: "option_unwrap_or",
        detail: "AIL source Option helper",
        documentation: "Namespaced alias that returns the value inside Option<T>, or a fallback when it is None.",
        insert_text: "option_unwrap_or(${1:option}, ${2:fallback})",
    },
    AclSymbol {
        label: "option.unwrap_or",
        detail: "AIL source Option helper",
        documentation: "Dotted alias that returns the value inside Option<T>, or a fallback when it is None.",
        insert_text: "option.unwrap_or(${1:option}, ${2:fallback})",
    },
    AclSymbol {
        label: "ok_or",
        detail: "AIL source Option helper",
        documentation: "Converts Option<T> to Result<T,E> using the supplied error when None.",
        insert_text: "ok_or(${1:option}, ${2:error})",
    },
    AclSymbol {
        label: "option_ok_or",
        detail: "AIL source Option helper",
        documentation: "Namespaced alias that converts Option<T> to Result<T,E> using the supplied error when None.",
        insert_text: "option_ok_or(${1:option}, ${2:error})",
    },
    AclSymbol {
        label: "option.ok_or",
        detail: "AIL source Option helper",
        documentation: "Dotted alias that converts Option<T> to Result<T,E> using the supplied error when None.",
        insert_text: "option.ok_or(${1:option}, ${2:error})",
    },
    AclSymbol {
        label: "result_unwrap_or",
        detail: "AIL source Result helper",
        documentation: "Returns the Ok value inside Result<T,E>, or a fallback when it is Err.",
        insert_text: "result_unwrap_or(${1:result}, ${2:fallback})",
    },
    AclSymbol {
        label: "result.unwrap_or",
        detail: "AIL source Result helper",
        documentation: "Dotted alias that returns the Ok value inside Result<T,E>, or a fallback when it is Err.",
        insert_text: "result.unwrap_or(${1:result}, ${2:fallback})",
    },
    AclSymbol {
        label: "first_or",
        detail: "AIL source List helper",
        documentation: "Returns the first List element when present, otherwise returns a fallback value.",
        insert_text: "first_or(${1:list}, ${2:fallback})",
    },
    AclSymbol {
        label: "last_or",
        detail: "AIL source List helper",
        documentation: "Returns the last List element when present, otherwise returns a fallback value.",
        insert_text: "last_or(${1:list}, ${2:fallback})",
    },
    AclSymbol {
        label: "get_or",
        detail: "AIL source List helper",
        documentation: "Returns the List element at an in-bounds index, otherwise returns a fallback value.",
        insert_text: "get_or(${1:list}, ${2:index}, ${3:fallback})",
    },
    AclSymbol {
        label: "list_get",
        detail: "AIL source List helper",
        documentation: "Returns Option<T> for a zero-based List index; None when out of bounds.",
        insert_text: "list_get(${1:list}, ${2:index})",
    },
    AclSymbol {
        label: "list.get",
        detail: "AIL source List helper",
        documentation: "Dotted alias that returns Option<T> for a zero-based List index.",
        insert_text: "list.get(${1:list}, ${2:index})",
    },
    AclSymbol {
        label: "queue_push_back",
        detail: "AIL source Queue helper",
        documentation: "Returns a queue List<T> with the supplied value appended at the back.",
        insert_text: "queue_push_back(${1:queue}, ${2:value})",
    },
    AclSymbol {
        label: "queue.push_back",
        detail: "AIL source Queue helper",
        documentation: "Dotted alias that appends a value at the back of a queue List<T>.",
        insert_text: "queue.push_back(${1:queue}, ${2:value})",
    },
    AclSymbol {
        label: "queue_pop_front",
        detail: "AIL source Queue helper",
        documentation: "Returns Option<Tuple<T,List<T>>> with the front value and remaining queue, or None when empty.",
        insert_text: "queue_pop_front(${1:queue})",
    },
    AclSymbol {
        label: "queue.pop_front",
        detail: "AIL source Queue helper",
        documentation: "Dotted alias that pops the front value and remaining queue, or None when empty.",
        insert_text: "queue.pop_front(${1:queue})",
    },
    AclSymbol {
        label: "queue_peek_front",
        detail: "AIL source Queue helper",
        documentation: "Returns Option<T> for the oldest queued value without removing it.",
        insert_text: "queue_peek_front(${1:queue})",
    },
    AclSymbol {
        label: "queue.peek_front",
        detail: "AIL source Queue helper",
        documentation: "Dotted alias that returns the oldest queued value without removing it.",
        insert_text: "queue.peek_front(${1:queue})",
    },
    AclSymbol {
        label: "queue_length",
        detail: "AIL source Queue helper",
        documentation: "Returns the number of entries in a queue List<T>.",
        insert_text: "queue_length(${1:queue})",
    },
    AclSymbol {
        label: "queue.length",
        detail: "AIL source Queue helper",
        documentation: "Dotted alias that returns the number of entries in a queue List<T>.",
        insert_text: "queue.length(${1:queue})",
    },
    AclSymbol {
        label: "queue_is_empty",
        detail: "AIL source Queue helper",
        documentation: "Returns true when the queue List<T> is empty.",
        insert_text: "queue_is_empty(${1:queue})",
    },
    AclSymbol {
        label: "queue.is_empty",
        detail: "AIL source Queue helper",
        documentation: "Dotted alias that returns true when a queue List<T> is empty.",
        insert_text: "queue.is_empty(${1:queue})",
    },
    AclSymbol {
        label: "list_push",
        detail: "AIL source List helper",
        documentation: "Returns a List<T> with the supplied value appended at the end.",
        insert_text: "list_push(${1:list}, ${2:value})",
    },
    AclSymbol {
        label: "list.push",
        detail: "AIL source List helper",
        documentation: "Dotted alias that appends a value at the end of a List<T>.",
        insert_text: "list.push(${1:list}, ${2:value})",
    },
    AclSymbol {
        label: "list_concat",
        detail: "AIL source List helper",
        documentation: "Returns a List<T> containing the first list followed by the second.",
        insert_text: "list_concat(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "list.concat",
        detail: "AIL source List helper",
        documentation: "Dotted alias that concatenates two List<T> values.",
        insert_text: "list.concat(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "set",
        detail: "AIL source Set builtin",
        documentation: "Constructs a typed Set<T> from same-typed values.",
        insert_text: "set(${1:value})",
    },
    AclSymbol {
        label: "tuple",
        detail: "AIL source Tuple builtin",
        documentation: "Constructs a typed Tuple<T...> from positional values.",
        insert_text: "tuple(${1:first}, ${2:second})",
    },
    AclSymbol {
        label: "tuple_length",
        detail: "AIL source Tuple helper",
        documentation: "Returns the arity of a Tuple<T...> value as Int.",
        insert_text: "tuple_length(${1:tuple})",
    },
    AclSymbol {
        label: "tuple_get",
        detail: "AIL source Tuple helper",
        documentation: "Returns Option<T> for a zero-based tuple index; None when out of bounds.",
        insert_text: "tuple_get(${1:tuple}, ${2:index})",
    },
    AclSymbol {
        label: "tuple_first",
        detail: "AIL source Tuple helper",
        documentation: "Returns Option<T> containing the first tuple element, or None for an empty tuple.",
        insert_text: "tuple_first(${1:tuple})",
    },
    AclSymbol {
        label: "tuple_second",
        detail: "AIL source Tuple helper",
        documentation: "Returns Option<T> containing the second tuple element, or None when absent.",
        insert_text: "tuple_second(${1:tuple})",
    },
    AclSymbol {
        label: "set_contains",
        detail: "AIL source Set helper",
        documentation: "Returns true when Set<T> contains the supplied value.",
        insert_text: "set_contains(${1:set}, ${2:value})",
    },
    AclSymbol {
        label: "set.contains",
        detail: "AIL source Set helper",
        documentation: "Dotted alias that returns true when Set<T> contains the supplied value.",
        insert_text: "set.contains(${1:set}, ${2:value})",
    },
    AclSymbol {
        label: "set_length",
        detail: "AIL source Set helper",
        documentation: "Returns the number of entries in a Set<T>.",
        insert_text: "set_length(${1:set})",
    },
    AclSymbol {
        label: "set.length",
        detail: "AIL source Set helper",
        documentation: "Dotted alias that returns the number of entries in a Set<T>.",
        insert_text: "set.length(${1:set})",
    },
    AclSymbol {
        label: "set_insert",
        detail: "AIL source Set helper",
        documentation: "Returns a Set<T> with the supplied value inserted.",
        insert_text: "set_insert(${1:set}, ${2:value})",
    },
    AclSymbol {
        label: "set.insert",
        detail: "AIL source Set helper",
        documentation: "Dotted alias that inserts a value into a Set<T>.",
        insert_text: "set.insert(${1:set}, ${2:value})",
    },
    AclSymbol {
        label: "map",
        detail: "AIL source Map builtin",
        documentation: "Constructs a typed Map<K,V> from key/value argument pairs.",
        insert_text: "map(${1:key}, ${2:value})",
    },
    AclSymbol {
        label: "map_get",
        detail: "AIL source Map helper",
        documentation: "Returns Option<V> for a Text key in Map<Text,V>; None when absent.",
        insert_text: "map_get(${1:map}, ${2:key})",
    },
    AclSymbol {
        label: "map.get",
        detail: "AIL source Map helper",
        documentation: "Dotted alias that returns Option<V> for a Text key in Map<Text,V>.",
        insert_text: "map.get(${1:map}, ${2:key})",
    },
    AclSymbol {
        label: "map_contains_key",
        detail: "AIL source Map helper",
        documentation: "Returns true when Map<Text,V> contains the Text key.",
        insert_text: "map_contains_key(${1:map}, ${2:key})",
    },
    AclSymbol {
        label: "map.contains_key",
        detail: "AIL source Map helper",
        documentation: "Dotted alias that returns true when Map<Text,V> contains the Text key.",
        insert_text: "map.contains_key(${1:map}, ${2:key})",
    },
    AclSymbol {
        label: "map_length",
        detail: "AIL source Map helper",
        documentation: "Returns the number of key/value entries in a Map<Text,V>.",
        insert_text: "map_length(${1:map})",
    },
    AclSymbol {
        label: "map.length",
        detail: "AIL source Map helper",
        documentation: "Dotted alias that returns the number of key/value entries in a Map<Text,V>.",
        insert_text: "map.length(${1:map})",
    },
    AclSymbol {
        label: "map_insert",
        detail: "AIL source Map helper",
        documentation: "Returns a Map<Text,V> with the Text key set to the supplied value.",
        insert_text: "map_insert(${1:map}, ${2:key}, ${3:value})",
    },
    AclSymbol {
        label: "map.insert",
        detail: "AIL source Map helper",
        documentation: "Dotted alias that sets a Text key to the supplied value in a Map<Text,V>.",
        insert_text: "map.insert(${1:map}, ${2:key}, ${3:value})",
    },
    AclSymbol {
        label: "record",
        detail: "AIL source Record builtin",
        documentation: "Constructs a typed Record<field:Type,...> from field/value pairs.",
        insert_text: "record(${1:field}, ${2:value})",
    },
    AclSymbol {
        label: "field",
        detail: "AIL source Record field access",
        documentation: "Reads a field from a typed Record<field:Type,...> value.",
        insert_text: "field(${1:record}, ${2:field})",
    },
    AclSymbol {
        label: "update",
        detail: "AIL source Record field update",
        documentation: "Returns a record with one typed field updated.",
        insert_text: "update(${1:record}, ${2:field}, ${3:value})",
    },
    AclSymbol {
        label: "print",
        detail: "AIL source log effect",
        documentation: "Writes a Text message through the log.write capability; the source item needs an explicit grant.",
        insert_text: "print(${1:\"message\"})",
    },
    AclSymbol {
        label: "log_write",
        detail: "AIL source log effect",
        documentation: "Namespaced alias for print(message); requires capability log.write and an explicit grant.",
        insert_text: "log_write(${1:\"message\"})",
    },
    AclSymbol {
        label: "effect_call",
        detail: "AIL source capability call",
        documentation: "Calls an external capability operation after the source item has an explicit grant.",
        insert_text: "effect_call(${1:log.write}, ${2:write}, ${3:\"message\"})",
    },
];
