use super::AclSymbol;

pub(super) const AIL_SOURCE_BUILTIN_SYMBOLS: &[AclSymbol] = &[
    AclSymbol {
        label: "add",
        detail: "AIL source Int builtin",
        documentation: "Adds two Int values and returns an Int.",
        insert_text: "add(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "sub",
        detail: "AIL source Int builtin",
        documentation: "Subtracts the second Int from the first and returns an Int.",
        insert_text: "sub(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "mul",
        detail: "AIL source Int builtin",
        documentation: "Multiplies two Int values and returns an Int.",
        insert_text: "mul(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "div",
        detail: "AIL source Int builtin",
        documentation: "Divides the first Int by the second and returns an Int.",
        insert_text: "div(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "eq",
        detail: "AIL source comparison builtin",
        documentation: "Compares two values of the same inferred type and returns Bool.",
        insert_text: "eq(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "gt",
        detail: "AIL source Int comparison builtin",
        documentation: "Returns Bool after checking whether the first Int is greater than the second.",
        insert_text: "gt(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_min",
        detail: "AIL source Int bounds helper",
        documentation: "Returns the smaller of two Int values.",
        insert_text: "int_min(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_max",
        detail: "AIL source Int bounds helper",
        documentation: "Returns the larger of two Int values.",
        insert_text: "int_max(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_clamp",
        detail: "AIL source Int bounds helper",
        documentation: "Constrains an Int value to an inclusive low/high range.",
        insert_text: "int_clamp(${1:value}, ${2:low}, ${3:high})",
    },
    AclSymbol {
        label: "int_abs_or",
        detail: "AIL source Int safety helper",
        documentation: "Returns the absolute value of an Int, or fallback for the minimum Int overflow case.",
        insert_text: "int_abs_or(${1:value}, ${2:fallback})",
    },
    AclSymbol {
        label: "int_neg_or",
        detail: "AIL source Int safety helper",
        documentation: "Negates an Int value, or returns fallback for the minimum Int overflow case.",
        insert_text: "int_neg_or(${1:value}, ${2:fallback})",
    },
    AclSymbol {
        label: "int_add_or",
        detail: "AIL source Int safety helper",
        documentation: "Adds two Int values, or returns fallback on signed overflow.",
        insert_text: "int_add_or(${1:left}, ${2:right}, ${3:fallback})",
    },
    AclSymbol {
        label: "int_sub_or",
        detail: "AIL source Int safety helper",
        documentation: "Subtracts two Int values, or returns fallback on signed overflow.",
        insert_text: "int_sub_or(${1:left}, ${2:right}, ${3:fallback})",
    },
    AclSymbol {
        label: "int_mul_or",
        detail: "AIL source Int safety helper",
        documentation: "Multiplies two Int values, or returns fallback on signed overflow.",
        insert_text: "int_mul_or(${1:left}, ${2:right}, ${3:fallback})",
    },
    AclSymbol {
        label: "int_saturating_add",
        detail: "AIL source Int safety helper",
        documentation: "Adds two Int values, clamping to Int bounds on signed overflow.",
        insert_text: "int_saturating_add(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_saturating_sub",
        detail: "AIL source Int safety helper",
        documentation: "Subtracts two Int values, clamping to Int bounds on signed overflow.",
        insert_text: "int_saturating_sub(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_saturating_mul",
        detail: "AIL source Int safety helper",
        documentation: "Multiplies two Int values, clamping to Int bounds on signed overflow.",
        insert_text: "int_saturating_mul(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_saturating_neg",
        detail: "AIL source Int safety helper",
        documentation: "Negates an Int value, clamping the minimum Int overflow case to Int max.",
        insert_text: "int_saturating_neg(${1:value})",
    },
    AclSymbol {
        label: "int_wrapping_add",
        detail: "AIL source Int explicit wrapping helper",
        documentation: "Adds two Int values with explicit two's-complement wrapping semantics.",
        insert_text: "int_wrapping_add(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_wrapping_sub",
        detail: "AIL source Int explicit wrapping helper",
        documentation: "Subtracts two Int values with explicit two's-complement wrapping semantics.",
        insert_text: "int_wrapping_sub(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_wrapping_mul",
        detail: "AIL source Int explicit wrapping helper",
        documentation: "Multiplies two Int values with explicit two's-complement wrapping semantics.",
        insert_text: "int_wrapping_mul(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_wrapping_neg",
        detail: "AIL source Int explicit wrapping helper",
        documentation: "Negates an Int value with explicit two's-complement wrapping semantics.",
        insert_text: "int_wrapping_neg(${1:value})",
    },
    AclSymbol {
        label: "int_bit_and",
        detail: "AIL source Int bitwise helper",
        documentation: "Computes the bitwise AND of two Int values.",
        insert_text: "int_bit_and(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_bit_or",
        detail: "AIL source Int bitwise helper",
        documentation: "Computes the bitwise OR of two Int values.",
        insert_text: "int_bit_or(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_bit_xor",
        detail: "AIL source Int bitwise helper",
        documentation: "Computes the bitwise XOR of two Int values.",
        insert_text: "int_bit_xor(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int_bit_not",
        detail: "AIL source Int bitwise helper",
        documentation: "Computes the bitwise NOT of an Int value.",
        insert_text: "int_bit_not(${1:value})",
    },
    AclSymbol {
        label: "int_shift_left",
        detail: "AIL source Int bit shift helper",
        documentation: "Shifts an Int value left by the given Int amount using wrapping shift-count semantics.",
        insert_text: "int_shift_left(${1:value}, ${2:amount})",
    },
    AclSymbol {
        label: "int_shift_right",
        detail: "AIL source Int bit shift helper",
        documentation: "Shifts an Int value right by the given Int amount using arithmetic signed semantics and wrapping shift-count semantics.",
        insert_text: "int_shift_right(${1:value}, ${2:amount})",
    },
    AclSymbol {
        label: "int_shift_right_unsigned",
        detail: "AIL source Int bit shift helper",
        documentation: "Shifts an Int value right by the given Int amount using logical unsigned semantics and wrapping shift-count semantics.",
        insert_text: "int_shift_right_unsigned(${1:value}, ${2:amount})",
    },
    AclSymbol {
        label: "int_div_or",
        detail: "AIL source Int safety helper",
        documentation: "Divides two Int values, or returns fallback on divide-by-zero or signed overflow.",
        insert_text: "int_div_or(${1:value}, ${2:divisor}, ${3:fallback})",
    },
    AclSymbol {
        label: "int_rem_or",
        detail: "AIL source Int safety helper",
        documentation: "Computes Int remainder, or returns fallback on divide-by-zero or signed overflow.",
        insert_text: "int_rem_or(${1:value}, ${2:divisor}, ${3:fallback})",
    },
    AclSymbol {
        label: "int.min",
        detail: "AIL source Int bounds helper",
        documentation: "Dotted alias that returns the smaller of two Int values.",
        insert_text: "int.min(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int.max",
        detail: "AIL source Int bounds helper",
        documentation: "Dotted alias that returns the larger of two Int values.",
        insert_text: "int.max(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int.clamp",
        detail: "AIL source Int bounds helper",
        documentation: "Dotted alias that constrains an Int value to an inclusive low/high range.",
        insert_text: "int.clamp(${1:value}, ${2:low}, ${3:high})",
    },
    AclSymbol {
        label: "int.abs_or",
        detail: "AIL source Int safety helper",
        documentation: "Dotted alias that returns absolute value, or fallback for minimum Int overflow.",
        insert_text: "int.abs_or(${1:value}, ${2:fallback})",
    },
    AclSymbol {
        label: "int.neg_or",
        detail: "AIL source Int safety helper",
        documentation: "Dotted alias that negates an Int value, or returns fallback on overflow.",
        insert_text: "int.neg_or(${1:value}, ${2:fallback})",
    },
    AclSymbol {
        label: "int.add_or",
        detail: "AIL source Int safety helper",
        documentation: "Dotted alias that adds two Int values, or returns fallback on signed overflow.",
        insert_text: "int.add_or(${1:left}, ${2:right}, ${3:fallback})",
    },
    AclSymbol {
        label: "int.sub_or",
        detail: "AIL source Int safety helper",
        documentation: "Dotted alias that subtracts two Int values, or returns fallback on signed overflow.",
        insert_text: "int.sub_or(${1:left}, ${2:right}, ${3:fallback})",
    },
    AclSymbol {
        label: "int.mul_or",
        detail: "AIL source Int safety helper",
        documentation: "Dotted alias that multiplies two Int values, or returns fallback on signed overflow.",
        insert_text: "int.mul_or(${1:left}, ${2:right}, ${3:fallback})",
    },
    AclSymbol {
        label: "int.div_or",
        detail: "AIL source Int safety helper",
        documentation: "Dotted alias that divides two Int values, or returns fallback on unsafe division.",
        insert_text: "int.div_or(${1:value}, ${2:divisor}, ${3:fallback})",
    },
    AclSymbol {
        label: "int.rem_or",
        detail: "AIL source Int safety helper",
        documentation: "Dotted alias that computes remainder, or returns fallback on unsafe division.",
        insert_text: "int.rem_or(${1:value}, ${2:divisor}, ${3:fallback})",
    },
    AclSymbol {
        label: "int.saturating_add",
        detail: "AIL source Int safety helper",
        documentation: "Dotted alias that adds two Int values, clamping to Int bounds on overflow.",
        insert_text: "int.saturating_add(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int.saturating_sub",
        detail: "AIL source Int safety helper",
        documentation: "Dotted alias that subtracts two Int values, clamping to Int bounds on overflow.",
        insert_text: "int.saturating_sub(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int.saturating_mul",
        detail: "AIL source Int safety helper",
        documentation: "Dotted alias that multiplies two Int values, clamping to Int bounds on overflow.",
        insert_text: "int.saturating_mul(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int.saturating_neg",
        detail: "AIL source Int safety helper",
        documentation: "Dotted alias that negates an Int value, clamping minimum Int overflow.",
        insert_text: "int.saturating_neg(${1:value})",
    },
    AclSymbol {
        label: "int.wrapping_add",
        detail: "AIL source Int explicit wrapping helper",
        documentation: "Dotted alias that adds with explicit two's-complement wrapping semantics.",
        insert_text: "int.wrapping_add(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int.wrapping_sub",
        detail: "AIL source Int explicit wrapping helper",
        documentation: "Dotted alias that subtracts with explicit two's-complement wrapping semantics.",
        insert_text: "int.wrapping_sub(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int.wrapping_mul",
        detail: "AIL source Int explicit wrapping helper",
        documentation: "Dotted alias that multiplies with explicit two's-complement wrapping semantics.",
        insert_text: "int.wrapping_mul(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int.wrapping_neg",
        detail: "AIL source Int explicit wrapping helper",
        documentation: "Dotted alias that negates with explicit two's-complement wrapping semantics.",
        insert_text: "int.wrapping_neg(${1:value})",
    },
    AclSymbol {
        label: "int.bit_and",
        detail: "AIL source Int bitwise helper",
        documentation: "Dotted alias that computes the bitwise AND of two Int values.",
        insert_text: "int.bit_and(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int.bit_or",
        detail: "AIL source Int bitwise helper",
        documentation: "Dotted alias that computes the bitwise OR of two Int values.",
        insert_text: "int.bit_or(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int.bit_xor",
        detail: "AIL source Int bitwise helper",
        documentation: "Dotted alias that computes the bitwise XOR of two Int values.",
        insert_text: "int.bit_xor(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "int.bit_not",
        detail: "AIL source Int bitwise helper",
        documentation: "Dotted alias that computes the bitwise NOT of an Int value.",
        insert_text: "int.bit_not(${1:value})",
    },
    AclSymbol {
        label: "int.shift_left",
        detail: "AIL source Int bit shift helper",
        documentation: "Dotted alias that shifts an Int value left by an Int amount.",
        insert_text: "int.shift_left(${1:value}, ${2:amount})",
    },
    AclSymbol {
        label: "int.shift_right",
        detail: "AIL source Int bit shift helper",
        documentation: "Dotted alias that shifts an Int value right with arithmetic signed semantics.",
        insert_text: "int.shift_right(${1:value}, ${2:amount})",
    },
    AclSymbol {
        label: "int.shift_right_unsigned",
        detail: "AIL source Int bit shift helper",
        documentation: "Dotted alias that shifts an Int value right with logical unsigned semantics.",
        insert_text: "int.shift_right_unsigned(${1:value}, ${2:amount})",
    },
    AclSymbol {
        label: "concat",
        detail: "AIL source Text builtin",
        documentation: "Concatenates two Text values and returns Text.",
        insert_text: "concat(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "len",
        detail: "AIL source sized builtin",
        documentation: "Returns the Int length of a Text or List value.",
        insert_text: "len(${1:value})",
    },
    AclSymbol {
        label: "text_length",
        detail: "AIL source Text helper",
        documentation: "Returns the byte length of a Text value.",
        insert_text: "text_length(${1:value})",
    },
    AclSymbol {
        label: "text.length",
        detail: "AIL source Text helper",
        documentation: "Dotted alias that returns the byte length of a Text value.",
        insert_text: "text.length(${1:value})",
    },
    AclSymbol {
        label: "text.len",
        detail: "AIL source Text helper",
        documentation: "Dotted alias that returns the byte length of a Text value.",
        insert_text: "text.len(${1:value})",
    },
    AclSymbol {
        label: "list_length",
        detail: "AIL source List helper",
        documentation: "Returns the length of a List value.",
        insert_text: "list_length(${1:list})",
    },
    AclSymbol {
        label: "list.length",
        detail: "AIL source List helper",
        documentation: "Dotted alias that returns the length of a List value.",
        insert_text: "list.length(${1:list})",
    },
    AclSymbol {
        label: "is_empty",
        detail: "AIL source sized predicate",
        documentation: "Returns true when a Text or List value has length 0.",
        insert_text: "is_empty(${1:value})",
    },
    AclSymbol {
        label: "text_is_empty",
        detail: "AIL source Text predicate",
        documentation: "Returns true when a Text value has length 0.",
        insert_text: "text_is_empty(${1:value})",
    },
    AclSymbol {
        label: "text.is_empty",
        detail: "AIL source Text predicate",
        documentation: "Dotted alias that returns true when a Text value has length 0.",
        insert_text: "text.is_empty(${1:value})",
    },
    AclSymbol {
        label: "list_is_empty",
        detail: "AIL source List predicate",
        documentation: "Returns true when a List value has length 0.",
        insert_text: "list_is_empty(${1:list})",
    },
    AclSymbol {
        label: "list.is_empty",
        detail: "AIL source List predicate",
        documentation: "Dotted alias that returns true when a List value has length 0.",
        insert_text: "list.is_empty(${1:list})",
    },
    AclSymbol {
        label: "text_eq",
        detail: "AIL source Text predicate",
        documentation: "Compares two Text values by content.",
        insert_text: "text_eq(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "text.eq",
        detail: "AIL source Text predicate",
        documentation: "Dotted alias that compares two Text values by content.",
        insert_text: "text.eq(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "text_trim",
        detail: "AIL source Text helper",
        documentation: "Returns Text with leading and trailing ASCII whitespace removed.",
        insert_text: "text_trim(${1:value})",
    },
    AclSymbol {
        label: "text.trim",
        detail: "AIL source Text helper",
        documentation: "Dotted alias that trims leading and trailing ASCII whitespace from Text.",
        insert_text: "text.trim(${1:value})",
    },
    AclSymbol {
        label: "text_contains",
        detail: "AIL source Text predicate",
        documentation: "Returns true when the first Text contains the second Text.",
        insert_text: "text_contains(${1:haystack}, ${2:needle})",
    },
    AclSymbol {
        label: "text.contains",
        detail: "AIL source Text predicate",
        documentation: "Dotted alias that returns true when the first Text contains the second Text.",
        insert_text: "text.contains(${1:haystack}, ${2:needle})",
    },
    AclSymbol {
        label: "text_index_of",
        detail: "AIL source Text search",
        documentation: "Returns the zero-based byte index of needle inside Text, or -1 when absent.",
        insert_text: "text_index_of(${1:haystack}, ${2:needle})",
    },
    AclSymbol {
        label: "text.index_of",
        detail: "AIL source Text search",
        documentation: "Dotted alias that returns the zero-based byte index of needle, or -1 when absent.",
        insert_text: "text.index_of(${1:haystack}, ${2:needle})",
    },
    AclSymbol {
        label: "text_parse_int_or",
        detail: "AIL source Text parser",
        documentation: "Parses an ASCII decimal Int from Text, or returns fallback when invalid.",
        insert_text: "text_parse_int_or(${1:value}, ${2:fallback})",
    },
    AclSymbol {
        label: "text.parse_int_or",
        detail: "AIL source Text parser",
        documentation: "Dotted alias that parses an ASCII decimal Int from Text, or returns fallback.",
        insert_text: "text.parse_int_or(${1:value}, ${2:fallback})",
    },
    AclSymbol {
        label: "text_byte_at_or",
        detail: "AIL source Text helper",
        documentation: "Returns the byte value at index, or fallback when the index is out of bounds.",
        insert_text: "text_byte_at_or(${1:value}, ${2:index}, ${3:fallback})",
    },
    AclSymbol {
        label: "text.byte_at_or",
        detail: "AIL source Text helper",
        documentation: "Dotted alias that returns the byte value at index, or fallback out of bounds.",
        insert_text: "text.byte_at_or(${1:value}, ${2:index}, ${3:fallback})",
    },
    AclSymbol {
        label: "text_slice",
        detail: "AIL source Text helper",
        documentation: "Returns a safe byte slice of Text from start for length bytes.",
        insert_text: "text_slice(${1:value}, ${2:start}, ${3:length})",
    },
    AclSymbol {
        label: "text.slice",
        detail: "AIL source Text helper",
        documentation: "Dotted alias that returns a safe byte slice of Text from start for length bytes.",
        insert_text: "text.slice(${1:value}, ${2:start}, ${3:length})",
    },
    AclSymbol {
        label: "text_replace_first",
        detail: "AIL source Text helper",
        documentation: "Replaces the first occurrence of needle in Text, or returns the original Text when absent.",
        insert_text: "text_replace_first(${1:value}, ${2:needle}, ${3:replacement})",
    },
    AclSymbol {
        label: "text.replace_first",
        detail: "AIL source Text helper",
        documentation: "Dotted alias that replaces the first occurrence of needle in Text.",
        insert_text: "text.replace_first(${1:value}, ${2:needle}, ${3:replacement})",
    },
    AclSymbol {
        label: "text_starts_with",
        detail: "AIL source Text predicate",
        documentation: "Returns true when Text starts with the given prefix.",
        insert_text: "text_starts_with(${1:haystack}, ${2:prefix})",
    },
    AclSymbol {
        label: "text.starts_with",
        detail: "AIL source Text predicate",
        documentation: "Dotted alias that returns true when Text starts with the given prefix.",
        insert_text: "text.starts_with(${1:haystack}, ${2:prefix})",
    },
    AclSymbol {
        label: "text_ends_with",
        detail: "AIL source Text predicate",
        documentation: "Returns true when Text ends with the given suffix.",
        insert_text: "text_ends_with(${1:haystack}, ${2:suffix})",
    },
    AclSymbol {
        label: "text.ends_with",
        detail: "AIL source Text predicate",
        documentation: "Dotted alias that returns true when Text ends with the given suffix.",
        insert_text: "text.ends_with(${1:haystack}, ${2:suffix})",
    },
    AclSymbol {
        label: "Some",
        detail: "AIL source Option constructor",
        documentation: "Builds Option<T> with a present value.",
        insert_text: "Some(${1:value})",
    },
    AclSymbol {
        label: "None",
        detail: "AIL source Option constructor",
        documentation: "Builds an empty Option<T> value.",
        insert_text: "None",
    },
    AclSymbol {
        label: "Ok",
        detail: "AIL source Result constructor",
        documentation: "Builds a Result<T,E> success value.",
        insert_text: "Ok(${1:value})",
    },
    AclSymbol {
        label: "Err",
        detail: "AIL source Result constructor",
        documentation: "Builds a Result<T,E> error value.",
        insert_text: "Err(${1:error})",
    },
    AclSymbol {
        label: "unwrap_or",
        detail: "AIL source Option helper",
        documentation: "Returns the value inside Option<T>, or a fallback when it is None.",
        insert_text: "unwrap_or(${1:option}, ${2:fallback})",
    },
    AclSymbol {
        label: "option_unwrap_or",
        detail: "AIL source Option helper",
        documentation: "Namespaced alias that returns the value inside Option<T>, or a fallback when it is None.",
        insert_text: "option_unwrap_or(${1:option}, ${2:fallback})",
    },
    AclSymbol {
        label: "option.unwrap_or",
        detail: "AIL source Option helper",
        documentation: "Dotted alias that returns the value inside Option<T>, or a fallback when it is None.",
        insert_text: "option.unwrap_or(${1:option}, ${2:fallback})",
    },
    AclSymbol {
        label: "ok_or",
        detail: "AIL source Option helper",
        documentation: "Converts Option<T> to Result<T,E> using the supplied error when None.",
        insert_text: "ok_or(${1:option}, ${2:error})",
    },
    AclSymbol {
        label: "option_ok_or",
        detail: "AIL source Option helper",
        documentation: "Namespaced alias that converts Option<T> to Result<T,E> using the supplied error when None.",
        insert_text: "option_ok_or(${1:option}, ${2:error})",
    },
    AclSymbol {
        label: "option.ok_or",
        detail: "AIL source Option helper",
        documentation: "Dotted alias that converts Option<T> to Result<T,E> using the supplied error when None.",
        insert_text: "option.ok_or(${1:option}, ${2:error})",
    },
    AclSymbol {
        label: "result_unwrap_or",
        detail: "AIL source Result helper",
        documentation: "Returns the Ok value inside Result<T,E>, or a fallback when it is Err.",
        insert_text: "result_unwrap_or(${1:result}, ${2:fallback})",
    },
    AclSymbol {
        label: "result.unwrap_or",
        detail: "AIL source Result helper",
        documentation: "Dotted alias that returns the Ok value inside Result<T,E>, or a fallback when it is Err.",
        insert_text: "result.unwrap_or(${1:result}, ${2:fallback})",
    },
    AclSymbol {
        label: "first_or",
        detail: "AIL source List helper",
        documentation: "Returns the first List element when present, otherwise returns a fallback value.",
        insert_text: "first_or(${1:list}, ${2:fallback})",
    },
    AclSymbol {
        label: "last_or",
        detail: "AIL source List helper",
        documentation: "Returns the last List element when present, otherwise returns a fallback value.",
        insert_text: "last_or(${1:list}, ${2:fallback})",
    },
    AclSymbol {
        label: "get_or",
        detail: "AIL source List helper",
        documentation: "Returns the List element at an in-bounds index, otherwise returns a fallback value.",
        insert_text: "get_or(${1:list}, ${2:index}, ${3:fallback})",
    },
    AclSymbol {
        label: "list_get",
        detail: "AIL source List helper",
        documentation: "Returns Option<T> for a zero-based List index; None when out of bounds.",
        insert_text: "list_get(${1:list}, ${2:index})",
    },
    AclSymbol {
        label: "list.get",
        detail: "AIL source List helper",
        documentation: "Dotted alias that returns Option<T> for a zero-based List index.",
        insert_text: "list.get(${1:list}, ${2:index})",
    },
    AclSymbol {
        label: "queue_push_back",
        detail: "AIL source Queue helper",
        documentation: "Returns a queue List<T> with the supplied value appended at the back.",
        insert_text: "queue_push_back(${1:queue}, ${2:value})",
    },
    AclSymbol {
        label: "queue.push_back",
        detail: "AIL source Queue helper",
        documentation: "Dotted alias that appends a value at the back of a queue List<T>.",
        insert_text: "queue.push_back(${1:queue}, ${2:value})",
    },
    AclSymbol {
        label: "queue_pop_front",
        detail: "AIL source Queue helper",
        documentation: "Returns Option<Tuple<T,List<T>>> with the front value and remaining queue, or None when empty.",
        insert_text: "queue_pop_front(${1:queue})",
    },
    AclSymbol {
        label: "queue.pop_front",
        detail: "AIL source Queue helper",
        documentation: "Dotted alias that pops the front value and remaining queue, or None when empty.",
        insert_text: "queue.pop_front(${1:queue})",
    },
    AclSymbol {
        label: "queue_peek_front",
        detail: "AIL source Queue helper",
        documentation: "Returns Option<T> for the oldest queued value without removing it.",
        insert_text: "queue_peek_front(${1:queue})",
    },
    AclSymbol {
        label: "queue.peek_front",
        detail: "AIL source Queue helper",
        documentation: "Dotted alias that returns the oldest queued value without removing it.",
        insert_text: "queue.peek_front(${1:queue})",
    },
    AclSymbol {
        label: "queue_length",
        detail: "AIL source Queue helper",
        documentation: "Returns the number of entries in a queue List<T>.",
        insert_text: "queue_length(${1:queue})",
    },
    AclSymbol {
        label: "queue.length",
        detail: "AIL source Queue helper",
        documentation: "Dotted alias that returns the number of entries in a queue List<T>.",
        insert_text: "queue.length(${1:queue})",
    },
    AclSymbol {
        label: "queue_is_empty",
        detail: "AIL source Queue helper",
        documentation: "Returns true when the queue List<T> is empty.",
        insert_text: "queue_is_empty(${1:queue})",
    },
    AclSymbol {
        label: "queue.is_empty",
        detail: "AIL source Queue helper",
        documentation: "Dotted alias that returns true when a queue List<T> is empty.",
        insert_text: "queue.is_empty(${1:queue})",
    },
    AclSymbol {
        label: "list_push",
        detail: "AIL source List helper",
        documentation: "Returns a List<T> with the supplied value appended at the end.",
        insert_text: "list_push(${1:list}, ${2:value})",
    },
    AclSymbol {
        label: "list.push",
        detail: "AIL source List helper",
        documentation: "Dotted alias that appends a value at the end of a List<T>.",
        insert_text: "list.push(${1:list}, ${2:value})",
    },
    AclSymbol {
        label: "list_concat",
        detail: "AIL source List helper",
        documentation: "Returns a List<T> containing the first list followed by the second.",
        insert_text: "list_concat(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "list.concat",
        detail: "AIL source List helper",
        documentation: "Dotted alias that concatenates two List<T> values.",
        insert_text: "list.concat(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "set",
        detail: "AIL source Set builtin",
        documentation: "Constructs a typed Set<T> from same-typed values.",
        insert_text: "set(${1:value})",
    },
    AclSymbol {
        label: "tuple",
        detail: "AIL source Tuple builtin",
        documentation: "Constructs a typed Tuple<T...> from positional values.",
        insert_text: "tuple(${1:first}, ${2:second})",
    },
    AclSymbol {
        label: "tuple_length",
        detail: "AIL source Tuple helper",
        documentation: "Returns the arity of a Tuple<T...> value as Int.",
        insert_text: "tuple_length(${1:tuple})",
    },
    AclSymbol {
        label: "tuple.length",
        detail: "AIL source Tuple helper",
        documentation: "Dotted alias that returns the arity of a Tuple<T...> value as Int.",
        insert_text: "tuple.length(${1:tuple})",
    },
    AclSymbol {
        label: "tuple_get",
        detail: "AIL source Tuple helper",
        documentation: "Returns Option<T> for a zero-based tuple index; None when out of bounds.",
        insert_text: "tuple_get(${1:tuple}, ${2:index})",
    },
    AclSymbol {
        label: "tuple.get",
        detail: "AIL source Tuple helper",
        documentation: "Dotted alias that returns Option<T> for a zero-based tuple index.",
        insert_text: "tuple.get(${1:tuple}, ${2:index})",
    },
    AclSymbol {
        label: "tuple_first",
        detail: "AIL source Tuple helper",
        documentation: "Returns Option<T> containing the first tuple element, or None for an empty tuple.",
        insert_text: "tuple_first(${1:tuple})",
    },
    AclSymbol {
        label: "tuple.first",
        detail: "AIL source Tuple helper",
        documentation: "Dotted alias that returns Option<T> containing the first tuple element.",
        insert_text: "tuple.first(${1:tuple})",
    },
    AclSymbol {
        label: "tuple_second",
        detail: "AIL source Tuple helper",
        documentation: "Returns Option<T> containing the second tuple element, or None when absent.",
        insert_text: "tuple_second(${1:tuple})",
    },
    AclSymbol {
        label: "tuple.second",
        detail: "AIL source Tuple helper",
        documentation: "Dotted alias that returns Option<T> containing the second tuple element.",
        insert_text: "tuple.second(${1:tuple})",
    },
    AclSymbol {
        label: "set_contains",
        detail: "AIL source Set helper",
        documentation: "Returns true when Set<T> contains the supplied value.",
        insert_text: "set_contains(${1:set}, ${2:value})",
    },
    AclSymbol {
        label: "set.contains",
        detail: "AIL source Set helper",
        documentation: "Dotted alias that returns true when Set<T> contains the supplied value.",
        insert_text: "set.contains(${1:set}, ${2:value})",
    },
    AclSymbol {
        label: "set_length",
        detail: "AIL source Set helper",
        documentation: "Returns the number of entries in a Set<T>.",
        insert_text: "set_length(${1:set})",
    },
    AclSymbol {
        label: "set.length",
        detail: "AIL source Set helper",
        documentation: "Dotted alias that returns the number of entries in a Set<T>.",
        insert_text: "set.length(${1:set})",
    },
    AclSymbol {
        label: "set_insert",
        detail: "AIL source Set helper",
        documentation: "Returns a Set<T> with the supplied value inserted.",
        insert_text: "set_insert(${1:set}, ${2:value})",
    },
    AclSymbol {
        label: "set.insert",
        detail: "AIL source Set helper",
        documentation: "Dotted alias that inserts a value into a Set<T>.",
        insert_text: "set.insert(${1:set}, ${2:value})",
    },
    AclSymbol {
        label: "map",
        detail: "AIL source Map builtin",
        documentation: "Constructs a typed Map<K,V> from key/value argument pairs.",
        insert_text: "map(${1:key}, ${2:value})",
    },
    AclSymbol {
        label: "map_get",
        detail: "AIL source Map helper",
        documentation: "Returns Option<V> for a Text key in Map<Text,V>; None when absent.",
        insert_text: "map_get(${1:map}, ${2:key})",
    },
    AclSymbol {
        label: "map.get",
        detail: "AIL source Map helper",
        documentation: "Dotted alias that returns Option<V> for a Text key in Map<Text,V>.",
        insert_text: "map.get(${1:map}, ${2:key})",
    },
    AclSymbol {
        label: "map_contains_key",
        detail: "AIL source Map helper",
        documentation: "Returns true when Map<Text,V> contains the Text key.",
        insert_text: "map_contains_key(${1:map}, ${2:key})",
    },
    AclSymbol {
        label: "map.contains_key",
        detail: "AIL source Map helper",
        documentation: "Dotted alias that returns true when Map<Text,V> contains the Text key.",
        insert_text: "map.contains_key(${1:map}, ${2:key})",
    },
    AclSymbol {
        label: "map_length",
        detail: "AIL source Map helper",
        documentation: "Returns the number of key/value entries in a Map<Text,V>.",
        insert_text: "map_length(${1:map})",
    },
    AclSymbol {
        label: "map.length",
        detail: "AIL source Map helper",
        documentation: "Dotted alias that returns the number of key/value entries in a Map<Text,V>.",
        insert_text: "map.length(${1:map})",
    },
    AclSymbol {
        label: "map_insert",
        detail: "AIL source Map helper",
        documentation: "Returns a Map<Text,V> with the Text key set to the supplied value.",
        insert_text: "map_insert(${1:map}, ${2:key}, ${3:value})",
    },
    AclSymbol {
        label: "map.insert",
        detail: "AIL source Map helper",
        documentation: "Dotted alias that sets a Text key to the supplied value in a Map<Text,V>.",
        insert_text: "map.insert(${1:map}, ${2:key}, ${3:value})",
    },
    AclSymbol {
        label: "numeric_narrow_to_i32",
        detail: "AIL source Numeric helper",
        documentation: "Narrows an Int to the signed 32-bit range, returning Result<Int,Text> on overflow.",
        insert_text: "numeric_narrow_to_i32(${1:value})",
    },
    AclSymbol {
        label: "numeric.narrow_to_i32",
        detail: "AIL source Numeric helper",
        documentation: "Dotted alias that narrows an Int to the signed 32-bit range.",
        insert_text: "numeric.narrow_to_i32(${1:value})",
    },
    AclSymbol {
        label: "numeric_narrow_to_u32",
        detail: "AIL source Numeric helper",
        documentation: "Narrows an Int to the unsigned 32-bit range, returning Result<Int,Text> on overflow or negative input.",
        insert_text: "numeric_narrow_to_u32(${1:value})",
    },
    AclSymbol {
        label: "numeric.narrow_to_u32",
        detail: "AIL source Numeric helper",
        documentation: "Dotted alias that narrows an Int to the unsigned 32-bit range.",
        insert_text: "numeric.narrow_to_u32(${1:value})",
    },
    AclSymbol {
        label: "numeric_narrow_to_u64",
        detail: "AIL source Numeric helper",
        documentation: "Narrows an Int to a non-negative u64-compatible value, returning Result<Int,Text> on invalid input.",
        insert_text: "numeric_narrow_to_u64(${1:value})",
    },
    AclSymbol {
        label: "numeric.narrow_to_u64",
        detail: "AIL source Numeric helper",
        documentation: "Dotted alias that narrows an Int to a non-negative u64-compatible value.",
        insert_text: "numeric.narrow_to_u64(${1:value})",
    },
    AclSymbol {
        label: "numeric_narrow_to_i16",
        detail: "AIL source Numeric helper",
        documentation: "Narrows an Int to the signed 16-bit range, returning Result<Int,Text> on overflow.",
        insert_text: "numeric_narrow_to_i16(${1:value})",
    },
    AclSymbol {
        label: "numeric.narrow_to_i16",
        detail: "AIL source Numeric helper",
        documentation: "Dotted alias that narrows an Int to the signed 16-bit range.",
        insert_text: "numeric.narrow_to_i16(${1:value})",
    },
    AclSymbol {
        label: "numeric_narrow_to_u8",
        detail: "AIL source Numeric helper",
        documentation: "Narrows an Int to the unsigned 8-bit range, returning Result<Int,Text> on overflow or negative input.",
        insert_text: "numeric_narrow_to_u8(${1:value})",
    },
    AclSymbol {
        label: "numeric.narrow_to_u8",
        detail: "AIL source Numeric helper",
        documentation: "Dotted alias that narrows an Int to the unsigned 8-bit range.",
        insert_text: "numeric.narrow_to_u8(${1:value})",
    },
    AclSymbol {
        label: "crypto_hash",
        detail: "AIL source Crypto helper",
        documentation: "Computes a BLAKE3 hash over Bytes and returns hash Bytes.",
        insert_text: "crypto_hash(${1:bytes})",
    },
    AclSymbol {
        label: "crypto.hash",
        detail: "AIL source Crypto helper",
        documentation: "Dotted alias that computes a BLAKE3 hash over Bytes.",
        insert_text: "crypto.hash(${1:bytes})",
    },
    AclSymbol {
        label: "crypto_hmac",
        detail: "AIL source Crypto helper",
        documentation: "Computes keyed HMAC Bytes for a Bytes message.",
        insert_text: "crypto_hmac(${1:key}, ${2:message})",
    },
    AclSymbol {
        label: "crypto.hmac",
        detail: "AIL source Crypto helper",
        documentation: "Dotted alias that computes keyed HMAC Bytes for a Bytes message.",
        insert_text: "crypto.hmac(${1:key}, ${2:message})",
    },
    AclSymbol {
        label: "crypto_constant_time_eq",
        detail: "AIL source Crypto helper",
        documentation: "Compares two Bytes buffers without early-exit timing leaks.",
        insert_text: "crypto_constant_time_eq(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "crypto.constant_time_eq",
        detail: "AIL source Crypto helper",
        documentation: "Dotted alias that compares two Bytes buffers without early-exit timing leaks.",
        insert_text: "crypto.constant_time_eq(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "encoding_base64_encode",
        detail: "AIL source Encoding helper",
        documentation: "Encodes Bytes into standard Base64 Text.",
        insert_text: "encoding_base64_encode(${1:bytes})",
    },
    AclSymbol {
        label: "encoding.base64_encode",
        detail: "AIL source Encoding helper",
        documentation: "Dotted alias that encodes Bytes into standard Base64 Text.",
        insert_text: "encoding.base64_encode(${1:bytes})",
    },
    AclSymbol {
        label: "encoding_base64_decode",
        detail: "AIL source Encoding helper",
        documentation: "Decodes Base64 Text into Result<Bytes,Text> with a textual decode error.",
        insert_text: "encoding_base64_decode(${1:text})",
    },
    AclSymbol {
        label: "encoding.base64_decode",
        detail: "AIL source Encoding helper",
        documentation: "Dotted alias that decodes Base64 Text into Result<Bytes,Text>.",
        insert_text: "encoding.base64_decode(${1:text})",
    },
    AclSymbol {
        label: "encoding_hex_encode",
        detail: "AIL source Encoding helper",
        documentation: "Encodes Bytes into lowercase hexadecimal Text.",
        insert_text: "encoding_hex_encode(${1:bytes})",
    },
    AclSymbol {
        label: "encoding.hex_encode",
        detail: "AIL source Encoding helper",
        documentation: "Dotted alias that encodes Bytes into lowercase hexadecimal Text.",
        insert_text: "encoding.hex_encode(${1:bytes})",
    },
    AclSymbol {
        label: "encoding_hex_decode",
        detail: "AIL source Encoding helper",
        documentation: "Decodes hexadecimal Text into Result<Bytes,Text> with a textual decode error.",
        insert_text: "encoding_hex_decode(${1:text})",
    },
    AclSymbol {
        label: "encoding.hex_decode",
        detail: "AIL source Encoding helper",
        documentation: "Dotted alias that decodes hexadecimal Text into Result<Bytes,Text>.",
        insert_text: "encoding.hex_decode(${1:text})",
    },
    AclSymbol {
        label: "time_duration_since",
        detail: "AIL source Time helper",
        documentation: "Returns later_ms - earlier_ms for two epoch-millisecond Int instants.",
        insert_text: "time_duration_since(${1:later_ms}, ${2:earlier_ms})",
    },
    AclSymbol {
        label: "time.duration_since",
        detail: "AIL source Time helper",
        documentation: "Dotted alias that returns later_ms - earlier_ms for epoch-millisecond Int instants.",
        insert_text: "time.duration_since(${1:later_ms}, ${2:earlier_ms})",
    },
    AclSymbol {
        label: "time_add_duration",
        detail: "AIL source Time helper",
        documentation: "Adds a duration in milliseconds to an epoch-millisecond Int instant.",
        insert_text: "time_add_duration(${1:instant_ms}, ${2:duration_ms})",
    },
    AclSymbol {
        label: "time.add_duration",
        detail: "AIL source Time helper",
        documentation: "Dotted alias that adds a millisecond duration to an epoch-millisecond Int instant.",
        insert_text: "time.add_duration(${1:instant_ms}, ${2:duration_ms})",
    },
    AclSymbol {
        label: "time_instant_to_ms",
        detail: "AIL source Time helper",
        documentation: "Projects an epoch-millisecond Int instant to its millisecond value.",
        insert_text: "time_instant_to_ms(${1:instant_ms})",
    },
    AclSymbol {
        label: "time.instant_to_ms",
        detail: "AIL source Time helper",
        documentation: "Dotted alias that projects an epoch-millisecond Int instant to milliseconds.",
        insert_text: "time.instant_to_ms(${1:instant_ms})",
    },
    AclSymbol {
        label: "bytes_length",
        detail: "AIL source Bytes helper",
        documentation: "Returns the byte count of a Bytes buffer as Int.",
        insert_text: "bytes_length(${1:bytes})",
    },
    AclSymbol {
        label: "bytes.length",
        detail: "AIL source Bytes helper",
        documentation: "Dotted alias that returns the byte count of a Bytes buffer as Int.",
        insert_text: "bytes.length(${1:bytes})",
    },
    AclSymbol {
        label: "bytes_at",
        detail: "AIL source Bytes helper",
        documentation: "Returns Option<Int> for a byte value at index; None when out of bounds.",
        insert_text: "bytes_at(${1:bytes}, ${2:index})",
    },
    AclSymbol {
        label: "bytes.at",
        detail: "AIL source Bytes helper",
        documentation: "Dotted alias that returns Option<Int> for a byte value at index.",
        insert_text: "bytes.at(${1:bytes}, ${2:index})",
    },
    AclSymbol {
        label: "bytes_slice",
        detail: "AIL source Bytes helper",
        documentation: "Returns Option<Bytes> for an in-bounds byte slice [start..end].",
        insert_text: "bytes_slice(${1:bytes}, ${2:start}, ${3:end})",
    },
    AclSymbol {
        label: "bytes.slice",
        detail: "AIL source Bytes helper",
        documentation: "Dotted alias that returns Option<Bytes> for an in-bounds byte slice.",
        insert_text: "bytes.slice(${1:bytes}, ${2:start}, ${3:end})",
    },
    AclSymbol {
        label: "bytes_concat",
        detail: "AIL source Bytes helper",
        documentation: "Returns a new Bytes buffer containing the left buffer followed by the right buffer.",
        insert_text: "bytes_concat(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "bytes.concat",
        detail: "AIL source Bytes helper",
        documentation: "Dotted alias that concatenates two Bytes buffers.",
        insert_text: "bytes.concat(${1:left}, ${2:right})",
    },
    AclSymbol {
        label: "bytes_empty",
        detail: "AIL source Bytes helper",
        documentation: "Returns true when a Bytes buffer has length zero.",
        insert_text: "bytes_empty(${1:bytes})",
    },
    AclSymbol {
        label: "bytes.empty",
        detail: "AIL source Bytes helper",
        documentation: "Dotted alias that returns true when a Bytes buffer has length zero.",
        insert_text: "bytes.empty(${1:bytes})",
    },
    AclSymbol {
        label: "record",
        detail: "AIL source Record builtin",
        documentation: "Constructs a typed Record<field:Type,...> from field/value pairs.",
        insert_text: "record(${1:field}, ${2:value})",
    },
    AclSymbol {
        label: "field",
        detail: "AIL source Record field access",
        documentation: "Reads a field from a typed Record<field:Type,...> value.",
        insert_text: "field(${1:record}, ${2:field})",
    },
    AclSymbol {
        label: "update",
        detail: "AIL source Record field update",
        documentation: "Returns a record with one typed field updated.",
        insert_text: "update(${1:record}, ${2:field}, ${3:value})",
    },
    AclSymbol {
        label: "print",
        detail: "AIL source log effect",
        documentation: "Writes a Text message through the log.write capability; the source item needs an explicit grant.",
        insert_text: "print(${1:\"message\"})",
    },
    AclSymbol {
        label: "log_write",
        detail: "AIL source log effect",
        documentation: "Namespaced alias for print(message); requires capability log.write and an explicit grant.",
        insert_text: "log_write(${1:\"message\"})",
    },
    AclSymbol {
        label: "log.write",
        detail: "AIL source log effect",
        documentation: "Dotted alias for print(message); requires capability log.write and an explicit grant.",
        insert_text: "log.write(${1:\"message\"})",
    },
    AclSymbol {
        label: "effect_call",
        detail: "AIL source capability call",
        documentation: "Calls an external capability operation after the source item has an explicit grant.",
        insert_text: "effect_call(${1:log.write}, ${2:write}, ${3:\"message\"})",
    },
];
