use super::AclSymbol;

pub(super) const AIL_SOURCE_SYNTAX_SYMBOLS: &[AclSymbol] = &[
    AclSymbol {
        label: "module",
        detail: "AIL source module",
        documentation: "Declares the source module namespace for functions, tests, and grants.",
        insert_text: "module ${1:name}",
    },
    AclSymbol {
        label: "use",
        detail: "AIL source import",
        documentation: "Imports another local .ail source file with an explicit relative path.",
        insert_text: "use \"./${1:file}.ail\"",
    },
    AclSymbol {
        label: "capability",
        detail: "AIL source capability",
        documentation: "Declares an external capability such as log.write before granting it to source items.",
        insert_text: "capability ${1:log.write}",
    },
    AclSymbol {
        label: "fn",
        detail: "AIL source function",
        documentation: "Declares a typed AIL source function that lowers into the semantic graph.",
        insert_text: "fn ${1:name}(${2:x}: ${3:Int}) -> ${4:Int} = ${5:add(x, 1)}",
    },
    AclSymbol {
        label: "Int",
        detail: "AIL source builtin type",
        documentation: "Signed integer type used by AIL source arithmetic and comparison helpers.",
        insert_text: "Int",
    },
    AclSymbol {
        label: "Bool",
        detail: "AIL source builtin type",
        documentation: "Boolean type returned by predicates, comparisons, and conditional expressions.",
        insert_text: "Bool",
    },
    AclSymbol {
        label: "Text",
        detail: "AIL source builtin type",
        documentation: "UTF-8 text type used by source string literals and text helpers.",
        insert_text: "Text",
    },
    AclSymbol {
        label: "List",
        detail: "AIL source generic type",
        documentation: "Parameterized list type written as List<T> for ordered homogeneous values.",
        insert_text: "List<${1:Int}>",
    },
    AclSymbol {
        label: "Record",
        detail: "AIL source generic type",
        documentation: "Parameterized record type written as Record<field:Type,...> for named fields.",
        insert_text: "Record<${1:field}:${2:Int}>",
    },
    AclSymbol {
        label: "Option",
        detail: "AIL source generic type",
        documentation: "Parameterized optional type written as Option<T> and constructed with Some(value) or None.",
        insert_text: "Option<${1:Int}>",
    },
    AclSymbol {
        label: "Result",
        detail: "AIL source generic type",
        documentation: "Parameterized success/error type written as Result<T,E> and constructed with Ok(value) or Err(error).",
        insert_text: "Result<${1:Int}, ${2:Text}>",
    },
    AclSymbol {
        label: "const",
        detail: "AIL source constant",
        documentation: "Declares a typed top-level source constant, lowered as a zero-argument semantic function.",
        insert_text: "const ${1:name}: ${2:Int} = ${3:42}",
    },
    AclSymbol {
        label: "test",
        detail: "AIL source test",
        documentation: "Declares an executable source test that `ail test --file` can discover and run.",
        insert_text: "test ${1:name} = ${2:eq(add(20, 22), 42)}",
    },
    AclSymbol {
        label: "grant",
        detail: "AIL source capability grant",
        documentation: "Grants a declared capability to a source function or test before effect calls are allowed.",
        insert_text: "grant ${1:main} ${2:log.write}",
    },
    AclSymbol {
        label: "let",
        detail: "AIL source local binding",
        documentation: "Introduces a local binding inside a block-bodied source function, with an optional type annotation.",
        insert_text: "let ${1:name}: ${2:Int} = ${3:value}",
    },
    AclSymbol {
        label: "return",
        detail: "AIL source return marker",
        documentation: "Marks the final expression returned from a source function, test, if branch, or match arm block.",
        insert_text: "return ${1:value}",
    },
    AclSymbol {
        label: "if",
        detail: "AIL source conditional",
        documentation: "Evaluates a typed conditional expression with block branches and explicit return markers.",
        insert_text: "if ${1:condition} {\n    return ${2:then_expr}\n} else {\n    return ${3:else_expr}\n}",
    },
    AclSymbol {
        label: "else if",
        detail: "AIL source conditional branch",
        documentation: "Adds an else-if branch to a block conditional while preserving typed branch expressions.",
        insert_text: "else if ${1:condition} {\n    return ${2:then_expr}\n}",
    },
    AclSymbol {
        label: "match",
        detail: "AIL source pattern match",
        documentation: "Destructures Option/Result values or matches literals with block arms and explicit return markers.",
        insert_text: "match ${1:value} {\n    ${2:Some(v)} => {\n        return ${3:v}\n    }\n    ${4:None} => {\n        return ${5:fallback}\n    }\n}",
    },
    AclSymbol {
        label: "Some",
        detail: "AIL source Option constructor",
        documentation: "Constructs an Option<T> value containing a payload.",
        insert_text: "Some(${1:value})",
    },
    AclSymbol {
        label: "None",
        detail: "AIL source Option constructor",
        documentation: "Constructs an empty Option<T> value.",
        insert_text: "None",
    },
    AclSymbol {
        label: "Ok",
        detail: "AIL source Result constructor",
        documentation: "Constructs a Result<T,E> success value.",
        insert_text: "Ok(${1:value})",
    },
    AclSymbol {
        label: "Err",
        detail: "AIL source Result constructor",
        documentation: "Constructs a Result<T,E> error value.",
        insert_text: "Err(${1:error})",
    },
    AclSymbol {
        label: "unwrap_or",
        detail: "AIL source Option helper",
        documentation: "Returns the value inside Some(value), or a fallback when the Option is None.",
        insert_text: "unwrap_or(${1:option}, ${2:fallback})",
    },
    AclSymbol {
        label: "is_some",
        detail: "AIL source Option predicate",
        documentation: "Returns true when an Option value is Some(_), false when it is None.",
        insert_text: "is_some(${1:option})",
    },
    AclSymbol {
        label: "is_none",
        detail: "AIL source Option predicate",
        documentation: "Returns true when an Option value is None, false when it is Some(_).",
        insert_text: "is_none(${1:option})",
    },
    AclSymbol {
        label: "option_is_some",
        detail: "AIL source Option predicate",
        documentation: "Namespaced alias for is_some(option).",
        insert_text: "option_is_some(${1:option})",
    },
    AclSymbol {
        label: "option.is_some",
        detail: "AIL source Option predicate",
        documentation: "Dotted alias for is_some(option).",
        insert_text: "option.is_some(${1:option})",
    },
    AclSymbol {
        label: "option_is_none",
        detail: "AIL source Option predicate",
        documentation: "Namespaced alias for is_none(option).",
        insert_text: "option_is_none(${1:option})",
    },
    AclSymbol {
        label: "option.is_none",
        detail: "AIL source Option predicate",
        documentation: "Dotted alias for is_none(option).",
        insert_text: "option.is_none(${1:option})",
    },
    AclSymbol {
        label: "is_ok",
        detail: "AIL source Result predicate",
        documentation: "Returns true when a Result value is Ok(_), false when it is Err(_).",
        insert_text: "is_ok(${1:result})",
    },
    AclSymbol {
        label: "is_err",
        detail: "AIL source Result predicate",
        documentation: "Returns true when a Result value is Err(_), false when it is Ok(_).",
        insert_text: "is_err(${1:result})",
    },
    AclSymbol {
        label: "result_is_ok",
        detail: "AIL source Result predicate",
        documentation: "Namespaced alias for is_ok(result).",
        insert_text: "result_is_ok(${1:result})",
    },
    AclSymbol {
        label: "result.is_ok",
        detail: "AIL source Result predicate",
        documentation: "Dotted alias for is_ok(result).",
        insert_text: "result.is_ok(${1:result})",
    },
    AclSymbol {
        label: "result_is_err",
        detail: "AIL source Result predicate",
        documentation: "Namespaced alias for is_err(result).",
        insert_text: "result_is_err(${1:result})",
    },
    AclSymbol {
        label: "result.is_err",
        detail: "AIL source Result predicate",
        documentation: "Dotted alias for is_err(result).",
        insert_text: "result.is_err(${1:result})",
    },
    AclSymbol {
        label: "+",
        detail: "AIL source Int infix operator",
        documentation: "Adds two Int expressions; equivalent to add(left, right).",
        insert_text: "${1:left} + ${2:right}",
    },
    AclSymbol {
        label: "-",
        detail: "AIL source Int operator",
        documentation: "Subtracts two Int expressions, or negates one expression when used as unary minus.",
        insert_text: "${1:left} - ${2:right}",
    },
    AclSymbol {
        label: "*",
        detail: "AIL source Int infix operator",
        documentation: "Multiplies two Int expressions; equivalent to mul(left, right).",
        insert_text: "${1:left} * ${2:right}",
    },
    AclSymbol {
        label: "/",
        detail: "AIL source Int infix operator",
        documentation: "Divides two Int expressions; equivalent to div(left, right).",
        insert_text: "${1:left} / ${2:right}",
    },
    AclSymbol {
        label: "%",
        detail: "AIL source Int infix operator",
        documentation: "Computes the Int remainder; equivalent to mod(left, right).",
        insert_text: "${1:left} % ${2:right}",
    },
    AclSymbol {
        label: "++",
        detail: "AIL source Text infix operator",
        documentation: "Concatenates two Text expressions; equivalent to concat(left, right).",
        insert_text: "${1:left} ++ ${2:right}",
    },
    AclSymbol {
        label: "==",
        detail: "AIL source equality operator",
        documentation: "Compares two expressions of the same inferred type; equivalent to eq(left, right).",
        insert_text: "${1:left} == ${2:right}",
    },
    AclSymbol {
        label: "!=",
        detail: "AIL source inequality operator",
        documentation: "Compares two expressions of the same inferred type; equivalent to ne(left, right).",
        insert_text: "${1:left} != ${2:right}",
    },
    AclSymbol {
        label: ">",
        detail: "AIL source Int comparison operator",
        documentation: "Checks whether the left Int is greater than the right Int; equivalent to gt(left, right).",
        insert_text: "${1:left} > ${2:right}",
    },
    AclSymbol {
        label: ">=",
        detail: "AIL source Int comparison operator",
        documentation: "Checks whether the left Int is greater than or equal to the right Int; equivalent to ge(left, right).",
        insert_text: "${1:left} >= ${2:right}",
    },
    AclSymbol {
        label: "<",
        detail: "AIL source Int comparison operator",
        documentation: "Checks whether the left Int is less than the right Int; equivalent to lt(left, right).",
        insert_text: "${1:left} < ${2:right}",
    },
    AclSymbol {
        label: "<=",
        detail: "AIL source Int comparison operator",
        documentation: "Checks whether the left Int is less than or equal to the right Int; equivalent to le(left, right).",
        insert_text: "${1:left} <= ${2:right}",
    },
    AclSymbol {
        label: "&&",
        detail: "AIL source Bool infix operator",
        documentation: "Combines two Bool expressions with logical and; equivalent to and(left, right).",
        insert_text: "${1:left} && ${2:right}",
    },
    AclSymbol {
        label: "||",
        detail: "AIL source Bool infix operator",
        documentation: "Combines two Bool expressions with logical or; equivalent to or(left, right).",
        insert_text: "${1:left} || ${2:right}",
    },
    AclSymbol {
        label: "!",
        detail: "AIL source Bool unary operator",
        documentation: "Negates a Bool expression; equivalent to not(expr).",
        insert_text: "!${1:expr}",
    },
    AclSymbol {
        label: ".",
        detail: "AIL source Record field operator",
        documentation: "Reads a field from a typed Record value; equivalent to field(record, name).",
        insert_text: "${1:record}.${2:field}",
    },
    AclSymbol {
        label: "{",
        detail: "AIL source Record literal",
        documentation: "Constructs a typed Record<field:Type,...> value with ergonomic field syntax.",
        insert_text: "{ ${1:field}: ${2:value} }",
    },
    AclSymbol {
        label: "...",
        detail: "AIL source Record update spread",
        documentation: "Copies a Record base inside a literal and updates typed fields; equivalent to update(record, field, value).",
        insert_text: "{ ...${1:record}, ${2:field}: ${3:value} }",
    },
];
