// ── ail-stdlib::random ────────────────────────────────────────────────────
//
// Seeded random generation for the AIL `std.random` module.
//
// # Rules (from docs/stdlib.md)
//
// - randomness is not pure
// - deterministic and crypto randomness are separate
//
// Deterministic: LCG seeded by caller.
// Crypto: type-level marker only (actual crypto random bytes require
//   the `crypto.random.bytes` capability provided by the runtime).

// ── Random capability contracts ──────────────────────────────────────────

/// Runtime capability labels exposed by `std.random` operations.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RandomCapability {
    /// Deterministic RNG seeded by the caller; no host entropy grant needed.
    DeterministicSeed,
    /// Cryptographically secure random bytes provided by the host.
    CryptoBytes,
}

impl RandomCapability {
    pub fn label(self) -> &'static str {
        match self {
            RandomCapability::DeterministicSeed => "random.seeded",
            RandomCapability::CryptoBytes => "crypto.random.bytes",
        }
    }
}

impl std::fmt::Display for RandomCapability {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.label())
    }
}

/// Stable operation families for random generation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RandomOperationKind {
    DeterministicInt,
    DeterministicFloat,
    DeterministicBytes,
    DeterministicIntRange,
    CryptoBytes,
}

impl RandomOperationKind {
    pub fn label(self) -> &'static str {
        match self {
            RandomOperationKind::DeterministicInt => "deterministic_int",
            RandomOperationKind::DeterministicFloat => "deterministic_float",
            RandomOperationKind::DeterministicBytes => "deterministic_bytes",
            RandomOperationKind::DeterministicIntRange => "deterministic_int_range",
            RandomOperationKind::CryptoBytes => "crypto_bytes",
        }
    }

    pub fn required_capability(self) -> RandomCapability {
        match self {
            RandomOperationKind::CryptoBytes => RandomCapability::CryptoBytes,
            RandomOperationKind::DeterministicInt
            | RandomOperationKind::DeterministicFloat
            | RandomOperationKind::DeterministicBytes
            | RandomOperationKind::DeterministicIntRange => RandomCapability::DeterministicSeed,
        }
    }

    pub fn grant_required(self) -> bool {
        matches!(self, RandomOperationKind::CryptoBytes)
    }
}

/// Redacted seed taxonomy. Diagnostics expose shape, never seed material.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RandomSeedShape {
    Zero,
    NonZero,
}

impl RandomSeedShape {
    pub fn label(self) -> &'static str {
        match self {
            RandomSeedShape::Zero => "zero",
            RandomSeedShape::NonZero => "non-zero",
        }
    }
}

/// Redacted byte-count taxonomy for random byte requests.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RandomByteCountShape {
    Empty,
    Bounded,
    TooLarge,
}

impl RandomByteCountShape {
    pub fn label(self) -> &'static str {
        match self {
            RandomByteCountShape::Empty => "empty",
            RandomByteCountShape::Bounded => "bounded",
            RandomByteCountShape::TooLarge => "too-large",
        }
    }

    pub fn is_allowed(self) -> bool {
        !matches!(self, RandomByteCountShape::TooLarge)
    }
}

/// Stable shape for integer range requests.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RandomRangeShape {
    Ascending,
    EmptyOrReversed,
}

impl RandomRangeShape {
    pub fn label(self) -> &'static str {
        match self {
            RandomRangeShape::Ascending => "ascending",
            RandomRangeShape::EmptyOrReversed => "empty-or-reversed",
        }
    }

    pub fn is_allowed(self) -> bool {
        matches!(self, RandomRangeShape::Ascending)
    }
}

/// Redacted random contract error. Does not echo seeds or generated bytes.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RandomShapeError {
    pub kind: RandomOperationKind,
    pub seed_shape: Option<RandomSeedShape>,
    pub byte_count_shape: Option<RandomByteCountShape>,
    pub range_shape: Option<RandomRangeShape>,
}

impl std::fmt::Display for RandomShapeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "invalid random operation shape: kind={}",
            self.kind.label()
        )?;
        if let Some(shape) = self.seed_shape {
            write!(f, ", seed_shape={}", shape.label())?;
        }
        if let Some(shape) = self.byte_count_shape {
            write!(f, ", byte_count_shape={}", shape.label())?;
        }
        if let Some(shape) = self.range_shape {
            write!(f, ", range_shape={}", shape.label())?;
        }
        Ok(())
    }
}

impl std::error::Error for RandomShapeError {}

/// Deny-by-default descriptor for a `std.random` operation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RandomOperationDescriptor {
    pub kind: RandomOperationKind,
    pub capability: RandomCapability,
    pub capability_label: &'static str,
    pub seed_shape: Option<RandomSeedShape>,
    pub byte_count_shape: Option<RandomByteCountShape>,
    pub range_shape: Option<RandomRangeShape>,
    pub grant_required: bool,
    pub ambient_access: bool,
    pub deterministic_replay: bool,
}

impl RandomOperationDescriptor {
    pub const DEFAULT_MAX_BYTES: usize = 1 << 20;

    pub fn deterministic_int(seed: Seed) -> Self {
        Self::new(
            RandomOperationKind::DeterministicInt,
            Some(seed),
            None,
            None,
            None,
            None,
        )
    }

    pub fn deterministic_float(seed: Seed) -> Self {
        Self::new(
            RandomOperationKind::DeterministicFloat,
            Some(seed),
            None,
            None,
            None,
            None,
        )
    }

    pub fn deterministic_bytes(seed: Seed, count: usize) -> Self {
        Self::new(
            RandomOperationKind::DeterministicBytes,
            Some(seed),
            Some(count),
            None,
            None,
            None,
        )
    }

    pub fn deterministic_int_range(seed: Seed, min: i64, max: i64) -> Self {
        Self::new(
            RandomOperationKind::DeterministicIntRange,
            Some(seed),
            None,
            Some(min),
            Some(max),
            None,
        )
    }

    pub fn crypto_bytes(count: usize) -> Self {
        Self::new(
            RandomOperationKind::CryptoBytes,
            None,
            Some(count),
            None,
            None,
            None,
        )
    }

    pub fn crypto_bytes_with_limit(count: usize, max_bytes: usize) -> Self {
        Self::new(
            RandomOperationKind::CryptoBytes,
            None,
            Some(count),
            None,
            None,
            Some(max_bytes),
        )
    }

    fn new(
        kind: RandomOperationKind,
        seed: Option<Seed>,
        count: Option<usize>,
        range_min: Option<i64>,
        range_max: Option<i64>,
        max_bytes: Option<usize>,
    ) -> Self {
        let capability = kind.required_capability();
        Self {
            kind,
            capability,
            capability_label: capability.label(),
            seed_shape: seed.map(random_seed_shape),
            byte_count_shape: count.map(|count| {
                random_byte_count_shape(count, max_bytes.unwrap_or(Self::DEFAULT_MAX_BYTES))
            }),
            range_shape: range_min
                .zip(range_max)
                .map(|(min, max)| random_range_shape(min, max)),
            grant_required: kind.grant_required(),
            ambient_access: false,
            deterministic_replay: capability == RandomCapability::DeterministicSeed,
        }
    }

    pub fn diagnostic_key(&self) -> String {
        let seed_shape = self
            .seed_shape
            .map(RandomSeedShape::label)
            .unwrap_or("no-seed");
        let byte_count_shape = self
            .byte_count_shape
            .map(RandomByteCountShape::label)
            .unwrap_or("no-bytes");
        let range_shape = self
            .range_shape
            .map(RandomRangeShape::label)
            .unwrap_or("no-range");
        format!(
            "std.random.{}:{}:{}:{}:{}",
            self.kind.label(),
            self.capability_label,
            seed_shape,
            byte_count_shape,
            range_shape
        )
    }

    pub fn validate_shape(&self) -> Result<(), RandomShapeError> {
        if self
            .byte_count_shape
            .map_or(false, |shape| !shape.is_allowed())
            || self.range_shape.map_or(false, |shape| !shape.is_allowed())
        {
            Err(RandomShapeError {
                kind: self.kind,
                seed_shape: self.seed_shape,
                byte_count_shape: self.byte_count_shape,
                range_shape: self.range_shape,
            })
        } else {
            Ok(())
        }
    }
}

pub fn random_seed_shape(seed: Seed) -> RandomSeedShape {
    if seed.0 == 0 {
        RandomSeedShape::Zero
    } else {
        RandomSeedShape::NonZero
    }
}

pub fn random_byte_count_shape(count: usize, max_bytes: usize) -> RandomByteCountShape {
    if count == 0 {
        RandomByteCountShape::Empty
    } else if count > max_bytes {
        RandomByteCountShape::TooLarge
    } else {
        RandomByteCountShape::Bounded
    }
}

pub fn random_range_shape(min: i64, max: i64) -> RandomRangeShape {
    if min < max {
        RandomRangeShape::Ascending
    } else {
        RandomRangeShape::EmptyOrReversed
    }
}

// ── Seed ──────────────────────────────────────────────────────────────────

/// Opaque seed for deterministic RNG.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Seed(pub u64);

impl Seed {
    pub fn new(v: u64) -> Self {
        Self(v)
    }
}

// ── DeterministicRng ──────────────────────────────────────────────────────

/// A simple Linear Congruential Generator (LCG) seeded deterministically.
///
/// Not suitable for security-sensitive use — use `CryptoRng` marker instead.
#[derive(Clone, Debug)]
pub struct DeterministicRng {
    state: u64,
}

impl DeterministicRng {
    /// Create a new RNG from the given seed.
    pub fn new(seed: Seed) -> Self {
        Self { state: seed.0 }
    }

    /// Advance the state and return the next `u64`.
    fn next_u64(&mut self) -> u64 {
        // Knuth multiplicative LCG (mod 2^64)
        self.state = self
            .state
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1_442_695_040_888_963_407);
        self.state
    }

    /// Generate a random `i64` value.
    pub fn random_int(&mut self) -> i64 {
        self.next_u64() as i64
    }

    /// Generate a random `f64` in `[0.0, 1.0)`.
    pub fn random_float(&mut self) -> f64 {
        (self.next_u64() >> 11) as f64 / (1u64 << 53) as f64
    }

    /// Generate `n` random bytes.
    pub fn random_bytes(&mut self, n: usize) -> Vec<u8> {
        (0..n).map(|_| (self.next_u64() & 0xFF) as u8).collect()
    }

    /// Generate a random `i64` in the range `[min, max)`.
    pub fn random_int_range(&mut self, min: i64, max: i64) -> Option<i64> {
        if min >= max {
            return None;
        }
        let range = (max as i128) - (min as i128);
        let offset = (self.next_u64() as u128 % range as u128) as i128;
        Some((min as i128 + offset) as i64)
    }
}

// ── CryptoRng ─────────────────────────────────────────────────────────────

/// Marker for cryptographically-secure randomness.
///
/// Actual crypto-random byte generation requires the `crypto.random.bytes`
/// capability provided by the AIL runtime host. This type is the API surface;
/// the runtime binds the implementation.
#[derive(Debug)]
pub struct CryptoRng;

impl CryptoRng {
    /// Marker constructor. Runtime must inject capability.
    pub fn new() -> Self {
        Self
    }
}

impl Default for CryptoRng {
    fn default() -> Self {
        Self::new()
    }
}

// ── RandomBytes ───────────────────────────────────────────────────────────

/// A fixed-size array of random bytes.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RandomBytes(pub Vec<u8>);

impl RandomBytes {
    pub fn new(bytes: Vec<u8>) -> Self {
        Self(bytes)
    }
    pub fn len(&self) -> usize {
        self.0.len()
    }
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
    pub fn as_slice(&self) -> &[u8] {
        &self.0
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn deterministic_range_handles_full_i64_domain_without_overflow() {
        let mut rng = DeterministicRng::new(Seed::new(42));

        let value = rng
            .random_int_range(i64::MIN, i64::MAX)
            .expect("full signed range should be representable");

        assert!(value < i64::MAX);
    }

    #[test]
    fn random_descriptors_are_capability_gated_and_redacted() {
        let deterministic = RandomOperationDescriptor::deterministic_bytes(Seed::new(7), 32);
        assert_eq!(deterministic.capability_label, "random.seeded");
        assert!(!deterministic.grant_required);
        assert!(!deterministic.ambient_access);
        assert!(deterministic.deterministic_replay);
        assert_eq!(
            deterministic.diagnostic_key(),
            "std.random.deterministic_bytes:random.seeded:non-zero:bounded:no-range"
        );

        let crypto = RandomOperationDescriptor::crypto_bytes(32);
        assert_eq!(crypto.capability_label, "crypto.random.bytes");
        assert!(crypto.grant_required);
        assert!(!crypto.ambient_access);
        assert!(!crypto.deterministic_replay);
        assert_eq!(
            crypto.diagnostic_key(),
            "std.random.crypto_bytes:crypto.random.bytes:no-seed:bounded:no-range"
        );
    }

    #[test]
    fn random_contract_validation_reports_shapes_without_values() {
        let oversized = RandomOperationDescriptor::crypto_bytes_with_limit(9, 8);
        let err = oversized
            .validate_shape()
            .expect_err("too-large byte count");
        assert_eq!(err.byte_count_shape, Some(RandomByteCountShape::TooLarge));
        assert_eq!(
            err.to_string(),
            "invalid random operation shape: kind=crypto_bytes, byte_count_shape=too-large"
        );

        let reversed = RandomOperationDescriptor::deterministic_int_range(Seed::new(99), 10, 10);
        let err = reversed.validate_shape().expect_err("empty range");
        assert_eq!(err.seed_shape, Some(RandomSeedShape::NonZero));
        assert_eq!(err.range_shape, Some(RandomRangeShape::EmptyOrReversed));
        assert_eq!(
            err.to_string(),
            "invalid random operation shape: kind=deterministic_int_range, seed_shape=non-zero, range_shape=empty-or-reversed"
        );
    }
}
