[package]
name    = "ail-package"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ail-core      = { workspace = true }
blake3        = { workspace = true }
ciborium      = { workspace = true }
ed25519-dalek = { workspace = true }
serde         = { workspace = true }
serde_json    = { workspace = true }
semver        = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

[lints]
workspace = true
