[package]
name    = "ail-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ail"
path = "src/main.rs"

[dependencies]
ail-change   = { workspace = true }
ail-compiler = { workspace = true }
ail-context  = { workspace = true }
ail-core     = { workspace = true }
ail-runtime  = { workspace = true }
ail-storage  = { workspace = true }
ail-verify   = { workspace = true }
blake3       = { workspace = true }
ciborium     = { workspace = true }
clap         = { workspace = true }
futures      = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
tokio        = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
assert_fs  = { workspace = true }
predicates = { workspace = true }
serde_json = { workspace = true }
tempfile   = { workspace = true }

[lints]
workspace = true
